version: '3'

services:
  php1:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/html
      - ./artisan:/var/www/html/artisan
    networks:
      - laravel
    depends_on:
      - mysql
    restart: always
    container_name: php1

  php2:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/html
      - ./artisan:/var/www/html/artisan
    networks:
      - laravel
    depends_on:
      - mysql
    restart: always
    container_name: php2

  nginx1:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./laravel1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    networks:
      - laravel
    restart: always 
    container_name: nginx1

  nginx2:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./laravel2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - laravel
    restart: always
    container_name: nginx2

  npm1:
    build: 
      context: .
      dockerfile: Dockerfile-npm
      args:
        - PORT=5173
    volumes:
      - .:/app
    networks:
      - laravel
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - php1

  npm2:
    build: 
      context: .
      dockerfile: Dockerfile-npm
      args:
        - PORT=5174
    volumes:
      - .:/app
    networks:
      - laravel
    restart: always
    ports:
      - "5174:5174"
    depends_on:
      - php2

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    restart: always
    container_name: mysql

networks:
  laravel:
    driver: bridge

volumes:
  db-data:
