version: '3'

services:
  php1:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
    restart: always

  php2:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
    restart: always

  nginx1:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - ./laravel1.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
    networks:
      - laravel
    restart: always 

  nginx2:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8082:80"
    volumes:
      - .:/var/www/html
      - ./laravel2.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
    networks:
      - laravel
    restart: always

  npm:
    build:
      context: .
      dockerfile: Dockerfile-npm
    volumes:
      - .:/var/www/html
    networks:
      - laravel
    restart: always

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes' 
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel
    restart: always

networks:
  laravel:
    driver: bridge

volumes:
  db-data:
