# Dockerfile - Nginx
FROM nginx:latest

# Copier la configuration Nginx
COPY nginx.conf /etc/nginx/nginx.conf
COPY laravel2.conf /etc/nginx/conf.d/default.conf

COPY . /var/www/html

# Exposer le port
EXPOSE 80
