FROM php:8.1.0-fpm

RUN docker-php-ext-install pdo pdo_mysql

ENV COMPOSER_ALLOW_SUPERUSER=1

RUN apt-get update && \
    apt-get install -y \
    libzip-dev \
    zip \
    netcat-openbsd \
    unzip \
    git \
    && docker-php-ext-install zip

COPY . /var/www/html

WORKDIR /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN php artisan key:generate

EXPOSE 9000

CMD ["php-fpm"]

COPY start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

RUN composer install

ENTRYPOINT ["start.sh"]
