# Étape 1: Utiliser une image Node.js officielle comme base
FROM node:latest

# Étape 2: Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Étape 3: Copier les fichiers de package.json et package-lock.json (si disponible) dans le conteneur
COPY package*.json ./

# Étape 4: Installer les dépendances du projet
RUN npm install

# Étape 5: Copier le reste des fichiers du projet dans le conteneur
COPY . .

# Étape 6: Construire l'application
RUN npm run build

# Étape 7: Exécuter l'application en mode développement
CMD ["npm", "run", "dev"]
