FROM node:latest

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json ./

# Installer toutes les dépendances
RUN npm install

# Copier le reste des fichiers de l'application
COPY . .

ENV PATH /app/node_modules/.bin:$PATH

# Exposer le port utilisé par Vite (si différent de celui par défaut)
EXPOSE 5173
